// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VAFA_MUL4.cpp"
#include "VAFA_MUL4___024root__DepSet_h16e897ca__0.cpp"
#include "VAFA_MUL4___024root__DepSet_ha6d57f7d__0.cpp"
#include "VAFA_MUL4___024root__Slow.cpp"
#include "VAFA_MUL4___024root__DepSet_h16e897ca__0__Slow.cpp"
#include "VAFA_MUL4___024root__DepSet_ha6d57f7d__0__Slow.cpp"
#include "VAFA_MUL4__Syms.cpp"
